services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitasy
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://fantasy:fantasy@postgres:5432/fantasy?sslmode=disable
    ports:
      - "50051:50051"

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    depends_on:
      - migrate
      - postgres
    environment:
      DATABASE_URL: postgres://fantasy:fantasy@postgres:5432/fantasy?sslmode=disable
    ports:
      - "50052:50052"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - auth
    ports:
      - "8080:8080"

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@postgres:5432/gitasy?sslmode=disable",
        "up"
      ]
    depends_on:
       postgres:
          condition: service_healthy

